# This is a basic workflow to help you get started with Actions

name: binding with the open source


on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Run a multi-line script for motivation
        run: echo open source is about giving back to community that help us grow 
          echo open source helps us create great things by working collaboratedly
          echo test so whats the point of thinking just dive into open source and set fire !!!


